spring:
  application:
    name: SecurityOAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <>
            client-secret: <>
server:
  port: ${PORT:8000}



